language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt
    - nvm install 6.4
    - nvm use 6.4
    - npm install
before_script:
    - python manage.py migrate
script:
    - python manage.py test
    - npm test
deploy:
  provider: heroku
  api_key:
    secure: 14cc27b8-a662-4fc8-a731-e2c6c02d0f26
